apiVersion: v1
kind: Pod
metadata:
  name: block2
spec:
  containers:
        - name: project_test-app-1
            image: php-test
            ports:
                - containerPort: 8000
    containers:
        - name: project_test-db-1
            image: mysql-test
            ports:
                - containerPort: 3306
    containers:
        - name: fileserver
            image: fileserver-test
            ports:
                - containerPort: 80
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: fileserver-claim0
  name: fileserver-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10000Mi
