apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -o ./kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fileserver
  name: fileserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fileserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -o ./kube
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fileserver
    spec:
      containers:
        - env:
            - name: BASEPATH
              value: /
            - name: BASIC_AUTH_ENABLED
              value: "false"
            - name: BASIC_AUTH_PASSWORD
              value: fileserver
            - name: BASIC_AUTH_REALM
              value: admin
            - name: BASIC_AUTH_USER
              value: admin
          image: fileserver-test
          name: fileserver
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /public
              name: fileserver-claim0
      restartPolicy: Always
      volumes:
        - name: fileserver-claim0
          persistentVolumeClaim:
            claimName: fileserver-claim0
