apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -o ./kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: video-server-router
  name: video-server-router
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: video-server-router
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -o ./kube
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: video-server-router
    spec:
      containers:
        - image: video-router-endpoint
          name: video-server-router
          ports:
            - containerPort: 8888
              protocol: TCP
          imagePullPolicy: Never
      restartPolicy: Always
