apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -o ./kube
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: video-server-router
  name: video-server-router
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: video-server-router
