FROM php:8.2-cli

# RUN apt update && apt -y install \
#   intstall libnginx-mod-http-lua \
#   && \
#   apt clean all

#COPY ./Content-Delivery-Network-Master/nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/src/app

# Install the PDO MySQL extension so we can database
RUN docker-php-ext-install pdo_mysql
RUN mkdir /usr/src/app/movies

COPY ./Content-Delivery-Network-Edge/php.ini-development /usr/local/etc/php/php.ini
COPY ./Content-Delivery-Network-Edge/download.php /usr/src/app/download.php

# Set up a web server
CMD ["php", "-S", "0.0.0.0:80"]

EXPOSE 80
