FROM mysql:8.0

# Set an insecure password
ENV MYSQL_ROOT_PASSWORD=cryhavokandletslipthedogsofwar

# Copy over our SQL queries
COPY ./VIDEO.php /VIDEO.sql

# Startup MySQL and run the queries
CMD ["mysqld", "--init-file=/init.sql"]
