FROM mysql:8.3.0

# Set an insecure password
ENV MYSQL_ROOT_PASSWORD=frog787toad404

# Copy over our SQL queries
COPY ./Database/VIDEO.sql /VIDEO.sql

VOLUME ["/var/lib/mysql"]

# Startup MySQL and run the queries
CMD ["mysqld", "--init-file=/VIDEO.sql"]
